//! # torrc Generator
//!
//! **Directory:** `src/tor/`
//!
//! Generates a fresh `torrc` file on every startup, ensuring the config
//! always matches `settings.toml`.  User edits to `torrc` are intentionally
//! overwritten; `settings.toml` is the single source of truth.
//!
//! All paths written into `torrc` are absolute so Tor can be started from
//! any working directory.

use std::path::{Path, PathBuf};

use crate::{config::TorConfig, Result};

/// Write a `torrc` file to `dest` using values from `config`.
///
/// - `data_dir`    — the `./rusthost-data/` base directory (used to resolve relative paths)
/// - `server_port` — the port the HTTP server is actually listening on
///   (used for `HiddenServicePort` mapping)
pub fn write(config: &TorConfig, data_dir: &Path, server_port: u16, dest: &Path) -> Result<()> {
    // Resolve all paths to absolute so torrc is unambiguous.
    // `absolute_create` creates the directory and canonicalizes the path.
    // `absolute_no_create` is used for HiddenServiceDir — Tor must create
    // that directory itself with mode 700; pre-creating it causes Tor to abort.
    let abs_data_dir = absolute_create(data_dir, &config.data_dir)?;
    let abs_hs_dir = absolute_no_create(data_dir, &config.hidden_service_dir);

    let content = format!(
        "# torrc — auto-generated by RustHost on every start.\n\
         # Edit settings.toml to change these values.\n\
         \n\
         DataDirectory {data_dir}\n\
         SocksPort {socks_port}\n\
         ControlPort {control_port}\n\
         Log {log_level} stdout\n\
         \n\
         HiddenServiceDir {hs_dir}\n\
         HiddenServicePort 80 127.0.0.1:{server_port}\n",
        data_dir = abs_data_dir.display(),
        socks_port = config.socks_port,
        control_port = config.control_port,
        log_level = config.log_level,
        hs_dir = abs_hs_dir.display(),
        server_port = server_port,
    );

    // Ensure the parent directory exists.
    if let Some(parent) = dest.parent() {
        std::fs::create_dir_all(parent)?;
    }

    std::fs::write(dest, content)?;
    log::debug!("torrc written to {}", dest.display());
    Ok(())
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

/// Resolve `relative` against `base`, creating the directory so that
/// `canonicalize` succeeds. Use only for directories Tor does NOT own.
fn absolute_create(base: &Path, relative: &str) -> Result<PathBuf> {
    let joined = base.join(relative);
    std::fs::create_dir_all(&joined)?;
    Ok(joined.canonicalize()?)
}

/// Resolve `relative` against `base` WITHOUT creating the directory.
///
/// Used for `HiddenServiceDir`: Tor must create this directory itself
/// with mode 700.  Pre-creating it causes Tor to abort with a permissions
/// error.
fn absolute_no_create(base: &Path, relative: &str) -> PathBuf {
    // `base` is already absolute (derived from `current_exe()`), so joining
    // is sufficient. We skip canonicalize because the path may not exist yet.
    base.join(relative)
}
